version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=pass
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./data:/var/lib/rabbitmq/mnesia
    networks:
      rabbitmq_net:
        aliases:
          - rabbitmq_host
volumes:
  data: {}
networks:
  rabbitmq_net:
    name: rabbitmq_network
    driver: bridge
